version: 2.1
jobs:
  build:
    working_directory: ~/content-player/player
    docker:
      - image: g33tha/plugin:test
        environment:
           player_version_number: $CIRCLE_BRANCH
           build_number: $CIRCLE_BUILD_NUM
           filter_plugins: false
           
    steps:
      - checkout:
          path: ~/content-player
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          
      - run: git clone https://github.com/project-sunbird/sunbird-content-plugins.git plugins -b $CIRCLE_BRANCH     
      - run: npm install
      - run: npm run build-preview ekstep
      - run: grunt compress:preview
      - run: grunt generate-libs
      - run: grunt build-jsdoc
      
      - run: grunt karma:app
      - store_artifacts:
          path: player/preview.zip
          destination: preview.zip
          
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths: ./node_modules

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
