---
# tasks file for deploy
- hosts: localhost
  tasks: 
        - name: copy dev
          shell: aws s3 cp dev/AppConfig.js s3://ekstep-public/preview/sandbox/
          tags: 
               - dev

        - name: copy QA
          shell: aws s3 cp qa/AppConfig.js s3://ekstep-public/preview/QA/
          tags: 
               - qa

        - name: copy Prod
          shell: aws s3 cp prod/AppConfig.js s3://ekstep-public/preview/production/
          tags: 
               - prod
